{
 "title": "All time data",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pallets",
    "label": "Pallets",
    "query": "SELECT DISTINCT section from pallets_methods_calls;"
   },
   {
    "name": "methods",
    "label": "methods",
    "query": "SELECT DISTINCT method from pallets_methods_calls;"
   },
   { "name": "parachains", "query": "Polkadot" },
   { "name": "bucket_interval", "label": "Time Resolution", "query": "1h,1d,1w" }
  ]
 },
 "panels": [
  { "title": "Pallets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pallets",
   "type": "graph",
   "gridPos": { "h": 14, "w": 17, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket_gapfill('$bucket_interval', time) AS time,\n  sum(calls) AS \"calls\", section\nFROM pallets_methods_calls\nWHERE\n  $__timeFilter(\"time\") AND method in($methods) AND section in($pallets)\n\nGROUP BY time_bucket_gapfill('$bucket_interval', pallets_methods_calls.time), section\n\nORDER BY 1"
    }
   ]
  },
  {
   "title": "All",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket_gapfill('$bucket_interval', time) as time ,\n  count(calls) as calls\n  \nFROM pallets_methods_calls\nWHERE\n  $__timeFilter(\"time\") AND section in($pallets) AND method in($methods)\nGROUP BY time_bucket_gapfill('$bucket_interval', pallets_methods_calls.time); \n\n"
    }
   ]
  },
  {
   "title": "Pallets calls",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket_gapfill('$bucket_interval', time) as time ,\n  sum(calls) as calls,\n  section\nFROM pallets_methods_calls\nWHERE\n  $__timeFilter(\"time\") AND section in($pallets) AND method in($methods)\nGROUP BY time_bucket_gapfill('$bucket_interval', pallets_methods_calls.time) , section\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Methods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true
  },
  {
   "title": "Methods",
   "type": "graph",
   "gridPos": { "h": 13, "w": 17, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket_gapfill('$bucket_interval', pallets_methods_calls.time) AS time,\n  sum(calls) AS \"calls\", method\nFROM pallets_methods_calls\nWHERE\n  $__timeFilter(\"time\") AND method in($methods) AND section in($pallets)\n\nGROUP BY time_bucket_gapfill('$bucket_interval', pallets_methods_calls.time), method\n\nORDER BY 1"
    }
   ]
  },
  {
   "title": "All",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket_gapfill('$bucket_interval', time) as time ,\n  sum(calls) as calls\n  \nFROM pallets_methods_calls\nWHERE\n  $__timeFilter(\"time\") AND section in($pallets) AND method in($methods)\nGROUP BY time_bucket_gapfill('$bucket_interval', pallets_methods_calls.time); \n\n"
    }
   ]
  },
  {
   "title": "Methods calls",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket_gapfill('$bucket_interval', time) as time ,\n  sum(calls) as calls,\n  method\nFROM pallets_methods_calls\nWHERE\n  $__timeFilter(\"time\") AND section in($pallets) AND method in($methods)\nGROUP BY time_bucket_gapfill('$bucket_interval', pallets_methods_calls.time) , method\nORDER BY time\n"
    }
   ]
  },
  { "title": "Specifics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Staking Pallet Calls",
   "type": "graph",
   "gridPos": { "h": 13, "w": 17, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket_gapfill('$bucket_interval', time) AS time,\n  sum(calls) AS \"calls\", method\nFROM pallets_methods_calls\nWHERE\n  $__timeFilter(\"time\") and section like 'staking'\n\nGROUP BY time_bucket_gapfill('$bucket_interval', pallets_methods_calls.time), method\n\nORDER BY 1"
    }
   ]
  },
  {
   "title": "All Staking",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket_gapfill('$bucket_interval', time) as time ,\n  count(calls) as calls\n  \nFROM pallets_methods_calls\nWHERE\n  $__timeFilter(\"time\") AND method in($methods) AND section like 'staking'\nGROUP BY time_bucket_gapfill('$bucket_interval', pallets_methods_calls.time); \n\n"
    }
   ]
  },
  {
   "title": "Staking calls",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket_gapfill('$bucket_interval', time) as time ,\n  sum(calls) as calls,\n  method\nFROM pallets_methods_calls\nWHERE\n  $__timeFilter(\"time\") AND section in($pallets) AND method in($methods) AND section LIKE 'staking'\nGROUP BY time_bucket_gapfill('$bucket_interval', pallets_methods_calls.time) , method\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "xcmPallet Calls",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket_gapfill('$bucket_interval', time) AS time,\n  sum(calls) AS \"calls\", method\nFROM pallets_methods_calls\nWHERE\n  $__timeFilter(\"time\") and section like 'xcmPallet'\n\nGROUP BY time_bucket_gapfill('$bucket_interval', pallets_methods_calls.time), method\n\nORDER BY 1"
    }
   ]
  }
 ]
}