{
 "title": "Runtimes",
 "tags": [ "dashb" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "pallets_var",
    "label": "Pallets",
    "query": {
     "query": "runtime_section_method_calls_per_block{}"
    }
   },
   {
    "name": "chain",
    "label": "Parachain",
    "query": {
     "query": "runtime_section_method_calls_per_block{}"
    }
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "finalized head of the chain",
   "type": "stat",
   "gridPos": { "h": 4, "w": 21, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_finalized_number{chain=~\"(?i:($chain))\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "block timestamp ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "runtime_timestamp_seconds{}" }
   ]
  },
  {
   "title": "pallets size by item",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "runtime_pallet_size{ chain=~\"(?i:($chain))\", pallet=~\"(?i:($pallets_var))\"}"
    }
   ]
  },
  {
   "title": "pallets size",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 5 },
   "targets": [
    {
     "expr": "runtime_pallet_size{ chain=~\"(?i:($chain))\", pallet=~\"(?i:($pallets_var))\"}"
    }
   ]
  },
  {
   "title": "block length",
   "type": "timeseries",
   "description": "block length in bytes",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "runtime_block_length_bytes{chain=~\"(?i:($chain))\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "block length",
   "type": "piechart",
   "description": "block length in bytes",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "runtime_block_length_bytes{chain=~\"(?i:($chain))\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "runtime weight mandatory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "runtime_weight{chain=~\"(?i:($chain))\" , class=\"mandatory\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "runtime weight normal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "runtime_weight{chain=~\"(?i:($chain))\" , class=\"normal\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "runtime weight operational",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "expr": "runtime_weight{chain=~\"(?i:($chain))\" , class=\"operational\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "extrinsics/block signed",
   "type": "timeseries",
   "description": "number of extrinsics in the block, labeled by signature type",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "runtime_extrinsics_count{chain=~\"(?i:($chain))\", type=\"signed\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "extrinsics/block unsigned",
   "type": "timeseries",
   "description": "number of extrinsics in the block, labeled by signature type",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "runtime_extrinsics_count{chain=~\"(?i:($chain))\", type=\"unsigned\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Balances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "total runtime issuance",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 17, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "runtime_total_issuance{chain=~\"(?i:($chain))\"}",
       "legendFormat": "{{chain}}"
      }
     ]
    },
    {
     "title": "total runtime issuance",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 7, "x": 17, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "runtime_total_issuance{chain=~\"(?i:($chain))\"}",
       "legendFormat": "{{chain}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transaction payment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "weight to fee multiplier",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "runtime_weight_to_fee_multiplier{chain=~\"(?i:($chain))\"}",
       "legendFormat": "{{chain}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Staking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "active validators",
     "type": "barchart",
     "description": "Total number of validators in staking system",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "runtime_validator_count{chain=~\"(?i:($chain))\", type=\"active\"}",
       "legendFormat": "{{chain}}"
      }
     ]
    },
    {
     "title": "intention validators",
     "type": "barchart",
     "description": "Total number of validators in staking system",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 4 },
     "targets": [
      {
       "expr": "runtime_validator_count{chain=~\"(?i:($chain))\", type=\"intention\"}",
       "legendFormat": "{{chain}}"
      }
     ]
    },
    {
     "title": "active nominators",
     "type": "barchart",
     "description": "Total number of nominators in staking system",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "runtime_nominator_count{chain=~\"(?i:($chain))\", type=\"active\"}",
       "legendFormat": "{{chain}}"
      }
     ]
    },
    {
     "title": "intention nominators",
     "type": "barchart",
     "description": "Total number of nominators in staking system",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 4 },
     "targets": [
      {
       "expr": "runtime_nominator_count{chain=~\"(?i:($chain))\", type=\"intention\"}",
       "legendFormat": "{{chain}}"
      }
     ]
    },
    {
     "title": "staked all",
     "type": "barchart",
     "description": "Total amount of staked tokens",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "runtime_stake{app=\"runtime-metrics\", instance=\"127.0.0.1:8000\", job=\"runtime\", chain=~\"(?i:($chain))\", type=\"all\"}",
       "legendFormat": "{{chain}}"
      }
     ]
    },
    {
     "title": "staked self",
     "type": "barchart",
     "description": "Total amount of staked tokens",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
     "targets": [
      {
       "expr": "runtime_stake{app=\"runtime-metrics\", instance=\"127.0.0.1:8000\", job=\"runtime\", chain=~\"(?i:($chain))\", type=\"self\"}",
       "legendFormat": "{{chain}}"
      }
     ]
    },
    {
     "title": "staked other",
     "type": "barchart",
     "description": "Total amount of staked tokens",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
     "targets": [
      {
       "expr": "runtime_stake{app=\"runtime-metrics\", instance=\"127.0.0.1:8000\", job=\"runtime\", chain=~\"(?i:($chain))\", type=\"other\"}",
       "legendFormat": "{{chain}}"
      }
     ]
    },
    {
     "title": "number of nodes per bag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "runtime_voter_list_node_per_bag{chain=~\"(?i:($chain))\"}"
      }
     ]
    },
    {
     "title": "runtime staking ledger",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
     "targets": [
      {
       "expr": "runtime_staking_ledger{chain=~\"(?i:($chain))\"}"
      }
     ]
    },
    {
     "title": "nodes in the voter list",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "runtime_voter_list_nodes{chain=~\"(?i:($chain))\"}"
      }
     ]
    },
    {
     "title": "number of voter list bags",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "runtime_voter_list_bags{chain=~\"(?i:($chain))\", type=\"active\"}"
      }
     ]
    }
   ]
  },
  { "title": "Multi phase", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "multi phase election signed",
   "type": "timeseries",
   "description": "Stats of the latest signed multi_phase submission",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "runtime_multi_phase_election_signed{chain=~\"(?i:($chain))\"}"
    }
   ]
  },
  {
   "title": "multi phase election store",
   "type": "timeseries",
   "description": "Stats of the latest signed multi_phase submission",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "runtime_multi_phase_election_score{chain=~\"(?i:($chain))\"}"
    }
   ]
  },
  {
   "title": "multi phase election snapshot",
   "type": "timeseries",
   "description": "Size of the latest multi_phase election snapshot",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "runtime_multi_phase_election_snapshot{chain=~\"(?i:($chain))\"}"
    }
   ]
  },
  {
   "title": "multi phase election unsigned",
   "type": "timeseries",
   "description": "Stats of the latest signed multi_phase submission",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "runtime_multi_phase_election_unsigned{chain=~\"(?i:($chain))\"}"
    }
   ]
  }
 ]
}