{
 "title": "XCM Transfers",
 "tags": [ "dashb" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "fromchain", "label": "from chain", "query": { "query": "runtime_xcm_transfers" } },
   { "name": "tochain", "label": "to chain", "query": { "query": "runtime_xcm_transfers" } }
  ]
 },
 "panels": [
  {
   "title": "XCM transfers to chain",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (tochain) (runtime_xcm_transfers{ chain=~\"(?i:($fromchain))\", tochain=~\"(?i:($tochain))\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "XCM to chain",
   "type": "piechart",
   "description": "pallets usage",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (tochain) (runtime_xcm_transfers{ chain=~\"(?i:($fromchain))\", tochain=~\"(?i:($tochain))\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "xcm transfers from chain",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (chain) (runtime_xcm_transfers{ chain=~\"(?i:($fromchain))\", tochain=~\"(?i:($tochain))\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "XCM from chain",
   "type": "piechart",
   "description": "pallets usage",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count by (chain) (runtime_xcm_transfers{ chain=~\"(?i:($fromchain))\", tochain=~\"(?i:($tochain))\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "XCM Transfers from chain",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "DOT" } },
   "targets": [
    {
     "expr": "sum by (chain) (runtime_xcm_transfers{ chain=~\"(?i:($fromchain))\", tochain=~\"(?i:($tochain))\"})"
    }
   ]
  },
  {
   "title": "XCM Transfers to chain",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 18, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "DOT" } },
   "targets": [
    {
     "expr": "sum by (tochain) (runtime_xcm_transfers{ chain=~\"(?i:($fromchain))\", tochain=~\"(?i:($tochain))\"})"
    }
   ]
  },
  {
   "title": "XCM Transfers All",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "runtime_xcm_transfers{ chain=~\"(?i:($fromchain))\", tochain=~\"(?i:($tochain))\"}"
    }
   ]
  },
  {
   "title": "XCM transfers from chain to chain",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "DOT" } },
   "targets": [
    {
     "expr": "runtime_xcm_transfers{ chain=~\"(?i:($fromchain))\", tochain=~\"(?i:($tochain))\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  }
 ]
}